Fixing issues with YAML merging

diff --git a/.pancake/bin/pancake b/.pancake/bin/pancake
--- a/.pancake/bin/pancake
+++ b/.pancake/bin/pancake
@@ -31,12 +31,12 @@ set -- "${POSITIONAL[@]}" # restore positional parameters
 
 PANDOC="pandoc"
 CONF="/root/.pancake"
-TMP="/tmp/pancake/"
+TMP="/tmp/pancake"
 
 declare -a IN
 if [ $# == 0 ]; then
     if [ ! ls *.md 2>/dev/null ] ; then
-        echo -e "\033[1;31mNo markdown files found!\033[0m"; 
+        echo -e "\033[1;31mNo markdown files found!\033[0m";
         exit 1;
     fi
     IN=$(ls *.md)
@@ -45,7 +45,7 @@ fi
 while [[ $# -gt 0 ]]
 do
 if [ ! ls $1 2>/dev/null ] ; then
-    echo -e "\033[1;31mFile '$i' not found !\033[0m"; 
+    echo -e "\033[1;31mFile '$i' not found !\033[0m";
     exit 1;
 fi
 
@@ -76,20 +76,22 @@ for i in $CONF/filters/* ; do
     FILTERS="$FILTERS --filter $i"
 done
 
-EXTRA=" --quiet"
+EXTRA=" --verbose"
+
 
 if [ "$PANCAKE_TYPE" == "pdf" ] ; then
     EXTRA="$EXTRA -t latex --pdf-engine tectonic"
 fi
 
-EXTRA=$CONF/pancake.yaml
+YAML=$CONF/pancake.yaml
 if ls *.yaml ; then
     for i in *.yaml ; do
-        EXTRA="$EXTRA $i"
+        YAML="$YAML $i"
     done
 fi
 mkdir $TMP 2>/dev/null
-python3 $CONF/bin/yaml-merge.py $EXTRA -o "$TMP/merged.yaml"
+echo "python3 $CONF/bin/yaml-merge.py $YAML -o "$TMP/merged.yaml""
+python3 $CONF/bin/yaml-merge.py $YAML -o "$TMP/merged.yaml"
 META="--metadata-file=$TMP/merged.yaml"
 
 echo -e "\033[1;33mConverting \033[0;1m$IN\033[1;33m to \033[0;1m$PANCAKE_OUTPUT\033[1;33m…\033[0m"
@@ -103,8 +105,8 @@ while true ; do
     fi
     MD5=$(md5sum $IN)
     FAIL=0
-    echo "$PANDOC $OPT $FILTERS $META $PANCAKE_OPTIONS $IN -o \"$PANCAKE_OUTPUT\""
-    $PANDOC $OPT $FILTERS $META $PANCAKE_OPTIONS $IN -o "$PANCAKE_OUTPUT" || FAIL=$?
+    echo "$PANDOC $OPT $FILTERS $EXTRA $META $PANCAKE_OPTIONS $IN -o \"$PANCAKE_OUTPUT\""
+    $PANDOC $OPT $FILTERS $EXTRA $META $PANCAKE_OPTIONS $IN -o "$PANCAKE_OUTPUT" || FAIL=$?
     OWNER=($(ls -ld ${IN[0]}))
     chown ${OWNER[2]}:${OWNER[3]} $PANCAKE_OUTPUT 2>/dev/null
     if [ $PANCAKE_ONCE ] ; then
